mode: daemonset
image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    datadog:
      api:
        site: "datadoghq.com"

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [datadog]
      traces:
        receivers: [otlp]
        exporters: [datadog]